import type { Metadata } from 'next';
import {
  LEGAL_DRAFT_DATE,
  LegalDocument,
  LegalLink,
  LegalList,
  LegalParagraph,
  Placeholder,
} from '@/components/legal/LegalDocument';
import { LEGAL_CONTACT_EMAIL, LEGAL_OPERATOR } from '@/lib/legal';

export const metadata: Metadata = {
  title: 'Terms of Service | MUSE',
  description:
    'The terms for using MUSE, an AI music companion that recommends songs from a few words, with no account needed.',
};

export default function TermsPage() {
  return (
    <LegalDocument
      title="Terms of Service"
      summary="MUSE is an AI music companion. You describe a mood or a moment, it suggests songs with a one-line reason each, checks them against public music catalogues, and gives you links to open them where you listen. These terms describe what you can expect from MUSE, what MUSE expects from you, and what happens when either side stops."
      draftDate={LEGAL_DRAFT_DATE}
      sections={[
        {
          id: 'agreement',
          title: 'The agreement',
          body: (
            <LegalParagraph>
              By using MUSE you agree to these terms with {LEGAL_OPERATOR}. If
              you do not agree, do not use MUSE. Questions go to{' '}
              <LegalLink href={`mailto:${LEGAL_CONTACT_EMAIL}`}>
                {LEGAL_CONTACT_EMAIL}
              </LegalLink>
              .
            </LegalParagraph>
          ),
        },
        {
          id: 'service',
          title: 'What MUSE is',
          body: (
            <>
              <LegalParagraph>
                MUSE lets you describe what you want to hear in plain words. An
                AI model suggests between eight and twelve songs, each with a
                one-line reason and a region tag, with Nigerian and African
                music first unless you switch to Global. MUSE then checks each
                song against the Deezer catalogue and the Apple iTunes Search
                API, labels what it could not confirm as unverified, and gives
                you links to search for each song on Audiomack, Boomplay,
                Spotify, Apple Music, YouTube Music, and Deezer, plus copy,
                download, and share actions. You do not need an account.
              </LegalParagraph>
              <LegalParagraph>
                MUSE does not stream or play music and does not host any
                recording. Opening a song takes you to a third-party service
                under that service&apos;s own terms; whether the song is
                available there, and at what price, is up to that service.
              </LegalParagraph>
              <LegalParagraph>
                Optional features let you add a public Last.fm profile or a
                Spotify data export file to get suggestions and a description of
                your taste that fit you better. Both are described in the{' '}
                <LegalLink href="/privacy">Privacy Policy</LegalLink>.
              </LegalParagraph>
            </>
          ),
        },
        {
          id: 'ai',
          title: 'AI generated content',
          body: (
            <>
              <LegalParagraph>
                Replies, the one-line reasons, playlist titles, and the words
                about your taste are generated by an AI model. They can be
                wrong, incomplete, or oddly phrased. MUSE checks every suggested
                song against public catalogues and drops suggestions whose
                artist cannot be found anywhere, but a song marked unverified
                may be misremembered or misattributed, and even a verified match
                can be the wrong version. Treat the words as suggestions, not
                facts, and check anything that matters to you.
              </LegalParagraph>
              <LegalParagraph>
                MUSE gives no professional, medical, or legal advice, and music
                suggestions are not a statement about you.
              </LegalParagraph>
            </>
          ),
        },
        {
          id: 'your-content',
          title: 'Your content',
          body: (
            <LegalParagraph>
              Your messages, taste snapshot, and anything you type stay yours.
              You give MUSE permission to process them to provide the service,
              including sending the parts described in the{' '}
              <LegalLink href="/privacy">Privacy Policy</LegalLink> to the AI
              provider and song names to the catalogue APIs. You are responsible
              for what you type; do not submit content that is unlawful, that
              belongs to someone else without their permission, or that is about
              another person without their consent. Lists you copy, download, or
              share are yours to use; the songs in them belong to their rights
              holders.
            </LegalParagraph>
          ),
        },
        {
          id: 'acceptable-use',
          title: 'Acceptable use',
          body: (
            <>
              <LegalParagraph>You agree not to:</LegalParagraph>
              <LegalList
                items={[
                  'Use MUSE for anything unlawful or to harm others.',
                  "Try to get around rate limits, the daily budget, or the human check, access other people's data, or interfere with the service.",
                  'Send automated traffic to MUSE or use it to build a data set, a competing catalogue, or a model.',
                  'Scrape, copy, or redistribute catalogue data or artwork obtained through MUSE beyond the copy, download, and share actions MUSE offers.',
                  "Use MUSE in a way that breaks the terms of Deezer, Apple, Last.fm, or, for testers, Spotify's Terms of Use and Developer Policy.",
                ]}
              />
            </>
          ),
        },
        {
          id: 'availability',
          title: 'Availability, limits, and changes',
          body: (
            <>
              <LegalParagraph>
                MUSE is an early product offered free of charge. Features may
                change, pause, or be removed. Requests are rate limited per
                visitor, and the service has a shared daily budget; when it is
                reached MUSE says it is resting and answers again the next day
                (West Africa Time). MUSE is offered without an uptime guarantee,
                and the catalogues, the AI provider, and the services behind the
                open-in links can be unavailable or change what they allow,
                which stops the matching parts of MUSE until that changes.
              </LegalParagraph>
              <LegalParagraph>
                A paid plan, MUSE Plus, is described on the Plus page but is not
                open. Nothing is charged and no card is asked for. When it
                opens, separate payment terms will be added here first, with
                Paystack as the payment processor, and no paid feature will
                require a Spotify account.
              </LegalParagraph>
            </>
          ),
        },
        {
          id: 'testers',
          title: 'Testers who sign in with Spotify',
          body: (
            <LegalParagraph>
              Spotify sign-in and &quot;Create in Spotify&quot; are available
              only to testers the operator has allow-listed or who hold a tester
              key. A tester connects through Spotify&apos;s own sign-in, can
              withdraw that access at any time from the Spotify account page
              under Apps, and remains bound by Spotify&apos;s Terms of Use and
              Privacy Policy. Nothing offered to the public depends on a Spotify
              account. MUSE is an independent product and is not affiliated
              with, endorsed by, or sponsored by Spotify, Deezer, Apple,
              Last.fm, Audiomack, Boomplay, or Google; see the{' '}
              <LegalLink href="/spotify-attribution">
                Spotify attribution
              </LegalLink>{' '}
              page.
            </LegalParagraph>
          ),
        },
        {
          id: 'ip',
          title: 'Intellectual property',
          body: (
            <LegalParagraph>
              Song titles, artist names, artwork, and other catalogue data
              belong to the respective rights holders and reach you through
              Deezer and Apple under their API terms, or through Spotify for
              testers. Service names in the open-in links are trademarks of
              their owners and are used only to say where a link goes. The MUSE
              name, design, and software belong to {LEGAL_OPERATOR}. Nothing in
              these terms gives you rights in any of these marks.
            </LegalParagraph>
          ),
        },
        {
          id: 'ending',
          title: 'Ending the agreement',
          body: (
            <LegalParagraph>
              You can stop at any time by closing MUSE and, if you like,
              clearing its data from your browser as the Privacy Policy
              describes; there is no account to close. A tester can delete the
              account in Settings or withdraw MUSE&apos;s access in Spotify. We
              may limit or end access for a breach of these terms. Sections that
              by their nature should survive, such as intellectual property and
              limitation of liability, survive.
            </LegalParagraph>
          ),
        },
        {
          id: 'liability',
          title: 'Disclaimers and limitation of liability',
          body: (
            <>
              <LegalParagraph>
                MUSE is provided as is and as available. To the fullest extent
                permitted by law, we make no warranties about accuracy, fitness
                for a particular purpose, or uninterrupted operation, and we are
                not liable for indirect, incidental, or consequential losses
                arising from your use of MUSE, from AI generated content, or
                from a third-party service you reach through a link.
              </LegalParagraph>
              <LegalParagraph>
                Nothing in these terms limits liability that cannot be limited
                under the law that applies to you, including consumer protection
                law in Nigeria.
              </LegalParagraph>
            </>
          ),
        },
        {
          id: 'law',
          title: 'Governing law',
          body: (
            <LegalParagraph>
              These terms are governed by the laws of{' '}
              <Placeholder>governing law</Placeholder>, and disputes go to the
              courts of <Placeholder>jurisdiction</Placeholder>, without taking
              away protections you have as a consumer where you live.
            </LegalParagraph>
          ),
        },
        {
          id: 'changes',
          title: 'Changes to these terms',
          body: (
            <LegalParagraph>
              When these terms change, the date at the top changes with them.
              Continuing to use MUSE after a change means you accept the new
              terms.
            </LegalParagraph>
          ),
        },
      ]}
      reviewNotes={[
        "Fill in the governing law and the jurisdiction (the operator is in Lagos; the Federal Republic of Nigeria and the courts of Lagos State are the obvious candidates, but this is the owner's and the lawyer's call).",
        'Have the disclaimers and the limitation of liability checked against the Federal Competition and Consumer Protection Act 2018 and consumer law in any other launch country.',
        'Confirm the minimum age wording with the Privacy Policy (NDPA 2023 treats anyone under 18 as a child).',
        'Add payment terms (price, billing period, cancellation, refunds, VAT, Paystack as processor) before PAYMENTS_ENABLED is turned on.',
        'Confirm the API terms of Deezer and Apple allow the attribution and the caching MUSE does, and that the search links to each service are acceptable to it.',
        'Verify every external link opens the intended page.',
      ]}
      references={[
        {
          label: 'Deezer API terms of use',
          href: 'https://developers.deezer.com/termsofuse',
        },
        {
          label: 'Apple Media Services terms (iTunes Search API)',
          href: 'https://www.apple.com/legal/internet-services/itunes/',
        },
        {
          label: 'Last.fm API terms of service',
          href: 'https://www.last.fm/api/tos',
        },
        {
          label: 'Spotify Terms of Use (testers)',
          href: 'https://www.spotify.com/legal/end-user-agreement/',
        },
        {
          label: 'Spotify Developer Policy (testers)',
          href: 'https://developer.spotify.com/policy',
        },
      ]}
    />
  );
}
