import type { Metadata } from 'next';
import {
  LEGAL_DRAFT_DATE,
  LegalDocument,
  LegalLink,
  LegalList,
  LegalParagraph,
  Placeholder,
} from '@/components/legal/LegalDocument';

export const metadata: Metadata = {
  title: 'Terms of Service | MUSE',
  description:
    'The terms for using MUSE, an AI music companion that works with your Spotify account.',
};

export default function TermsPage() {
  return (
    <LegalDocument
      title="Terms of Service"
      summary="MUSE is an AI music companion that works with your Spotify account. These terms describe what you can expect from MUSE, what MUSE expects from you, and what happens when either side stops."
      draftDate={LEGAL_DRAFT_DATE}
      sections={[
        {
          id: 'agreement',
          title: 'The agreement',
          body: (
            <LegalParagraph>
              By connecting your Spotify account to MUSE or using the app, you
              agree to these terms with <Placeholder>Operator name</Placeholder>
              , who operates MUSE. If you do not agree, do not use MUSE.
              Questions go to <Placeholder>contact email</Placeholder>.
            </LegalParagraph>
          ),
        },
        {
          id: 'service',
          title: 'What MUSE is',
          body: (
            <>
              <LegalParagraph>
                MUSE lets you describe what you want to hear in plain words,
                finds matching tracks in Spotify&apos;s catalogue, explains each
                pick in a line, creates playlists in your Spotify account, and
                describes your taste from your listening. You need a Spotify
                account to use it.
              </LegalParagraph>
              <LegalParagraph>
                Some features depend on Spotify&apos;s rules rather than ours.
                Controlling playback requires Spotify Premium and an active
                Spotify device. When Spotify is unavailable or changes what its
                API allows, the matching parts of MUSE stop working until that
                changes.
              </LegalParagraph>
            </>
          ),
        },
        {
          id: 'spotify',
          title: 'Your Spotify account',
          body: (
            <>
              <LegalParagraph>
                You connect MUSE through Spotify&apos;s own sign-in and can
                withdraw that access at any time from your Spotify account page
                under Apps. Your Spotify account remains governed by
                Spotify&apos;s Terms of Use and Privacy Policy.
              </LegalParagraph>
              <LegalParagraph>
                MUSE is an independent product. It is not affiliated with,
                endorsed by, or sponsored by Spotify. See the{' '}
                <LegalLink href="/spotify-attribution">
                  Spotify attribution
                </LegalLink>{' '}
                page.
              </LegalParagraph>
            </>
          ),
        },
        {
          id: 'your-content',
          title: 'Your content',
          body: (
            <LegalParagraph>
              Your messages, Memory notes, and playlist names stay yours. You
              give MUSE permission to process them to provide the service,
              including sending the parts described in the{' '}
              <LegalLink href="/privacy">Privacy Policy</LegalLink> to the AI
              provider. You are responsible for what you type; do not submit
              content that is unlawful or that you have no right to share.
            </LegalParagraph>
          ),
        },
        {
          id: 'ai',
          title: 'AI generated content',
          body: (
            <>
              <LegalParagraph>
                Replies, the one-line reasons, and your taste profile are
                generated by an AI model. They can be wrong, incomplete, or
                oddly phrased. Every track MUSE shows comes from a Spotify
                catalogue search; MUSE does not invent tracks, but the words
                around them are the model&apos;s and should be read as
                suggestions, not facts.
              </LegalParagraph>
              <LegalParagraph>
                MUSE gives no professional, medical, or legal advice, and music
                suggestions are not a statement about you.
              </LegalParagraph>
            </>
          ),
        },
        {
          id: 'acceptable-use',
          title: 'Acceptable use',
          body: (
            <>
              <LegalParagraph>You agree not to:</LegalParagraph>
              <LegalList
                items={[
                  'Use MUSE for anything unlawful or to harm others.',
                  "Try to get around rate limits, access other people's data, or interfere with the service.",
                  'Scrape, copy, or redistribute Spotify content obtained through MUSE.',
                  'Reverse engineer MUSE or use it to build a competing data set.',
                  "Use MUSE in a way that breaks Spotify's Terms of Use or Developer Policy.",
                ]}
              />
            </>
          ),
        },
        {
          id: 'availability',
          title: 'Availability and changes',
          body: (
            <LegalParagraph>
              MUSE is an early product. Features may change, pause, or be
              removed, and requests are rate limited to keep the service usable
              for everyone. MUSE is offered without an uptime guarantee. If an
              account abuses the service, we may limit or suspend it.
            </LegalParagraph>
          ),
        },
        {
          id: 'ip',
          title: 'Intellectual property',
          body: (
            <LegalParagraph>
              Music, artwork, and metadata belong to Spotify and the respective
              rights holders and are shown under Spotify&apos;s developer terms.
              The MUSE name, design, and software belong to{' '}
              <Placeholder>Operator name</Placeholder>. Nothing in these terms
              gives you rights in Spotify&apos;s or MUSE&apos;s marks.
            </LegalParagraph>
          ),
        },
        {
          id: 'ending',
          title: 'Ending the agreement',
          body: (
            <LegalParagraph>
              You can stop at any time by deleting your account in Settings,
              which removes the data MUSE holds about you as described in the
              Privacy Policy, or by withdrawing MUSE&apos;s access in Spotify.
              We may end or suspend access for a breach of these terms. Sections
              that by their nature should survive, such as intellectual property
              and limitation of liability, survive.
            </LegalParagraph>
          ),
        },
        {
          id: 'liability',
          title: 'Disclaimers and limitation of liability',
          body: (
            <>
              <LegalParagraph>
                MUSE is provided as is and as available. To the fullest extent
                permitted by law, we make no warranties about accuracy, fitness
                for a particular purpose, or uninterrupted operation, and we are
                not liable for indirect, incidental, or consequential losses
                arising from your use of MUSE.
              </LegalParagraph>
              <LegalParagraph>
                Nothing in these terms limits liability that cannot be limited
                under the law that applies to you.
              </LegalParagraph>
            </>
          ),
        },
        {
          id: 'law',
          title: 'Governing law',
          body: (
            <LegalParagraph>
              These terms are governed by the laws of{' '}
              <Placeholder>governing law</Placeholder>, and disputes go to the
              courts of <Placeholder>jurisdiction</Placeholder>, without taking
              away protections you have as a consumer where you live.
            </LegalParagraph>
          ),
        },
        {
          id: 'changes',
          title: 'Changes to these terms',
          body: (
            <LegalParagraph>
              When these terms change, the date at the top changes with them.
              Continuing to use MUSE after a change means you accept the new
              terms.
            </LegalParagraph>
          ),
        },
      ]}
      reviewNotes={[
        'Fill in the operator name, the contact email, the governing law, and the jurisdiction.',
        'Have the disclaimers and the limitation of liability checked against consumer law in the launch countries, starting with Nigeria.',
        'Confirm the minimum age requirement for the launch countries.',
        'Verify every external link opens the intended page.',
      ]}
      references={[
        {
          label: 'Spotify Terms of Use',
          href: 'https://www.spotify.com/legal/end-user-agreement/',
        },
        {
          label: 'Spotify Developer Policy',
          href: 'https://developer.spotify.com/policy',
        },
        {
          label: 'Manage apps connected to your Spotify account',
          href: 'https://www.spotify.com/account/apps/',
        },
      ]}
    />
  );
}
